version: '3'
services:
  certificate-app:
    build: 
      context: .
    ports:
      - "80:80"
    restart: always
    volumes:
      # 如果需要在不重建镜像的情况下更新Nginx配置
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
